server:
  port: 8001

spring:
  redis:
    database: 0
    host: 192.168.25.170
    port: 6379
#    password: 123456


# 设置域名，在java代码中获取，这里是资源配置
website:
  domain-name: imoocnews.com

# 在dev环境开启mybatis的日志打印
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl